language: cpp
compiler: gcc
dist:     trusty
branches:
  only:
  - master
  - development

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libsdl1.2-dev libsdl-gfx1.2-dev libsdl-ttf2.0-dev
                            libx11-dev libjack-jackd2-dev
script:
  - autoreconf -if
  - ./configure
  - make
  - sudo make install
  - make installcheck
